server:
  port: 8085
spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://192.168.1.52:3306/internetstore?useSSL=false
    username: store
    password: 111111